version: '3.7'

services:
  web:
    build: ./store
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./store/:/www/store/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=bookstore_db

volumes:
  postgres_data: